version: '3'

services:
  tds-default:
    image: thredds-performance-tests:5.5-SNAPSHOT
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:443:8443"
      - "127.0.0.1:8443:8443"
    container_name: thredds-performance-tests
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigDefault.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"

  tds-no-caching:
    image: thredds-performance-tests:5.5-SNAPSHOT
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:443:8443"
      - "127.0.0.1:8443:8443"
    container_name: thredds-performance-tests
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigNoCaching.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"
