version: '3'

services:
  tds-caching:
    image: thredds-performance-tests:latest
    ports:
      - "8080:8080"
      - "443:8443"
      - "8443:8443"
    container_name: tds-caching
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigDefault.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"

  tds-no-caching:
    image: thredds-performance-tests:latest
    ports:
      - "8080:8080"
      - "443:8443"
      - "8443:8443"
    container_name: tds-no-caching
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigNoCaching.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"

  tds-caching-network-host:
    image: thredds-performance-tests:latest
    network_mode: host
    container_name: tds-caching-network-host
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigDefault.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"

  tds-no-caching-network-host:
    image: thredds-performance-tests:latest
    network_mode: host
    container_name: tds-no-caching-network-host
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml:ro
      - ./thredds/threddsConfigNoCaching.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml:ro
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml:ro
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/:ro
      - ${DATA_DIR}:/usr/local/tomcat/content/thredds/public/testdata/:ro
    env_file:
      - "compose.env"
