version: '3'

services:
  tds-default:
    image: thredds-performance-tests:5.5-SNAPSHOT
    ports:
      - "8080:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds-performance-tests
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./thredds/threddsConfigDefault.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/
      - ./data/:/usr/local/tomcat/content/thredds/public/testdata/
    env_file:
      - "compose.env"

  tds-no-caching:
    image: thredds-performance-tests:5.5-SNAPSHOT
    ports:
      - "8080:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds-performance-tests
    volumes:
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./thredds/threddsConfigNoCaching.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - ./thredds/wmsConfigDefault.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml
      - ./thredds/catalogs/:/usr/local/tomcat/content/thredds/catalogs/
      - ./data/:/usr/local/tomcat/content/thredds/public/testdata/
    env_file:
      - "compose.env"
